<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyVersion>1.9.9</AssemblyVersion>
    <Authors>Davide Mauri</Authors>
    <Copyright>Davide Mauri</Copyright>
    <Description>Efficently copy database tables from one SQL Server/Azure SQL database to another</Description>
    <FileVersion>1.9.9</FileVersion>
    <NeutralLanguage>en</NeutralLanguage>
    <OutputType>Exe</OutputType>
    <PackageId>SmartBulkCopy</PackageId>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/yorek/smartbulkcopy</PackageProjectUrl>
    <Product>Smart Bulk Copy</Product>
    <RepositoryType>Git</RepositoryType>
    <RepositoryUrl>https://github.com/yorek/smartbulkcopy</RepositoryUrl>
    <TargetFramework>net8.0</TargetFramework>
    <Title>SmartBulkCopy</Title>
    <Version>1.9.9</Version>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\hack\Microsoft.SqlServer.Types.Hack.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="*.config.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="*.config">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Data.SqlClient" Version="5.1.2" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.2" />
    <PackageReference Include="Dapper" Version="2.1.44" />
    <PackageReference Include="NLog.Extensions.Logging" Version="5.3.5" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="9.0.2" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.CommandLine" Version="8.0.0" />
  </ItemGroup>
</Project>