<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyVersion>1.9.9</AssemblyVersion>
    <Authors>Davide Mauri</Authors>
    <Copyright>Davide Mauri</Copyright>
    <Description>Efficently copy database tables from one SQL Server/Azure SQL database to another</Description>
    <FileVersion>1.9.9</FileVersion>
    <IsPackable>false</IsPackable>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/yorek/smartbulkcopy</PackageProjectUrl>
    <Product>Smart Bulk Copy</Product>
    <RepositoryType>GIT</RepositoryType>
    <RepositoryUrl>https://github.com/yorek/smartbulkcopy</RepositoryUrl>
    <TargetFramework>net8.0</TargetFramework>
    <Title>SmartBulkCopy.Tests</Title>
    <Version>1.9.9</Version>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\client\SmartBulkCopy.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="*.config.test.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="*.config.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="*.config">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="*.env">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="NUnit" Version="*" />
    <PackageReference Include="NLog.Extensions.Logging" Version="5.3.14" />
    <PackageReference Include="DotNetEnv" Version="3.1.1" />
    <PackageReference Include="NUnit3TestAdapter" Version="5.1.0" />
    <PackageReference Include="nunit" Version="4.3.2" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
  </ItemGroup>
</Project>