<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Microsoft.SqlServer.Types</AssemblyName>
    <Authors>Davide Mauri</Authors>
    <Company></Company>
    <Copyright>Davide Mauri</Copyright>
    <Description>Mocked version of Microsoft.SqlServer.Types that only implements Write and Read behaviour to allow Bulk Load to work correctly on Geometry, Geographt and HierarchyId data types</Description>
    <Product>Microsoft.SqlServer.Types.Hack</Product>
    <RootNamespace>Microsoft.SqlServer.Types</RootNamespace>
    <TargetFramework>net8.0</TargetFramework>
    <Version>0.0.1.0</Version>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.SqlServer.Server" Version="1.0.0" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="5.1.2" />
  </ItemGroup>
</Project>